<<<<<<< HEAD
spring.datasource.url=${Test_DB_URL}
spring.datasource.username=${Test_DB_USERNAME}
spring.datasource.password=${Test_DB_PASSWORD}
=======
spring.datasource.url=${TEST_DB_URL}
spring.datasource.username=${TEST_DB_USERNAME}
spring.datasource.password=${TEST_DB_PASSWORD}
>>>>>>> 7b5957738d34b7fd1fdd99412f1eff4831574c37

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect